// Components
import Head from 'next/head'
import Layout from '../src/components/global/Layout'

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta
        content='Generated by create next app'
        name='description'
      />
      <link
        href='/favicon.ico'
        rel='icon'
      />
    </Head>

    <Layout>
      <h1>Website Coming Soon</h1>
    </Layout>
  </>
)

export default Home
