// Components
import Head from 'next/head'
import Layout from '../src/components/global/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>Website Coming Soon</h1>
      </Layout>
    </>
  )
}
